version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"   # root of your repo
    schedule:
      interval: "daily"
    groups:
      all-providers:
        patterns:
          - "*"      # matches all Terraform providers
        update-types:
          - "minor"
          - "patch"
